CREATE SEQUENCE user_id_seq START WITH 100 INCREMENT BY 1;

CREATE SEQUENCE user_settings_id_seq START WITH 100 INCREMENT BY 1;

CREATE SEQUENCE queue_id_seq START WITH 100 INCREMENT BY 1;

CREATE SEQUENCE notifications_id_seq START WITH 100 INCREMENT BY 1;

CREATE SEQUENCE user_queue_id_seq START WITH 100 INCREMENT BY 1;

CREATE SEQUENCE queue_pin_code2_id_seq START WITH 100 INCREMENT BY 1;

CREATE SEQUENCE queue_qr_code2_id_seq START WITH 100 INCREMENT BY 1;
