name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check message patterns
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(Add |Create |Fix |Update |Rework)(.+)(?:closes #[1-9])|Minor|Merge'
          error: 'Commit message must start with Add, Create, Fix, Update, Rework or Minor.'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
