name: telegram message
on: [pull_request, push]
jobs:
  if: failure()
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on build fail
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Build faild
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}